"""esquema inicial del dominio

Revision ID: b1e466eb9fff
Revises: 
Create Date: 2026-09-03 21:29:12.519555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1e466eb9fff'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incident_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('related_entity_type', sa.Enum('SUBMISSION', 'EVALUATION', 'GENERATION', 'LMS_INTEGRATION', name='incidententitytype', native_enum=False, length=32), nullable=False),
    sa.Column('related_entity_id', sa.Integer(), nullable=True),
    sa.Column('incident_type', sa.Enum('EXTRACTION_FAILED', 'EMPTY_DOCUMENT', 'SUBMISSION_TRUNCATED', 'SUSPICIOUS_CONTENT', 'GEMINI_TIMEOUT', 'GEMINI_HTTP_ERROR', 'GEMINI_BLOCKED', 'INVALID_AI_RESPONSE', 'AI_SCORE_CLAMPED', 'EVALUATION_FAILED', 'LMS_SEND_FAILED', name='incidenttype', native_enum=False, length=32), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'WARNING', 'ERROR', 'CRITICAL', name='incidentseverity', native_enum=False, length=32), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lms_integrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('SIMULATOR', 'LTI1_3', name='lmsintegrationtype', native_enum=False, length=32), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('TEACHER', 'ADMIN', name='userrole', native_enum=False, length=32), nullable=False),
    sa.Column('source', sa.Enum('LOCAL', 'LMS', name='usersource', native_enum=False, length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('external_id')
    )
    op.create_table('assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('course_name', sa.String(length=255), nullable=True),
    sa.Column('lms_integration_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lms_integration_id'], ['lms_integrations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rubrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'ARCHIVED', name='rubricstatus', native_enum=False, length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rubric_criteria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rubric_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('weight', sa.Numeric(precision=6, scale=2, asdecimal=False), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rubric_id'], ['rubrics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rubric_id', 'order', name='uq_criterion_order_per_rubric')
    )
    op.create_table('submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=True),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('student_identifier', sa.String(length=128), nullable=False),
    sa.Column('original_filename', sa.String(length=512), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('file_extension', sa.String(length=8), nullable=False),
    sa.Column('mime_type', sa.String(length=128), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('extraction_status', sa.Enum('PENDING', 'SUCCESS', 'FAILED', 'EMPTY', name='extractionstatus', native_enum=False, length=32), nullable=False),
    sa.Column('extraction_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evaluations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('rubric_id', sa.Integer(), nullable=False),
    sa.Column('rubric_version_snapshot', sa.JSON(), nullable=False),
    sa.Column('teacher_instructions', sa.Text(), nullable=True),
    sa.Column('general_feedback', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PROCESSING', 'AI_GENERATED', 'UNDER_REVIEW', 'APPROVED', 'FAILED', 'CANCELLED', name='evaluationstatus', native_enum=False, length=32), nullable=False),
    sa.Column('current_generation_id', sa.Integer(), nullable=True),
    sa.Column('final_total_score', sa.Numeric(precision=8, scale=2, asdecimal=False), nullable=True),
    sa.Column('final_max_score', sa.Numeric(precision=8, scale=2, asdecimal=False), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('sent_to_lms_at', sa.DateTime(), nullable=True),
    sa.Column('lms_result_payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['current_generation_id'], ['evaluation_generations.id'], name='fk_evaluation_current_generation', use_alter=True),
    sa.ForeignKeyConstraint(['rubric_id'], ['rubrics.id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('performance_levels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('criterion_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('score', sa.Numeric(precision=8, scale=2, asdecimal=False), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['criterion_id'], ['rubric_criteria.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('criterion_id', 'order', name='uq_level_order_per_criterion')
    )
    op.create_table('evaluation_criterion_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evaluation_id', sa.Integer(), nullable=False),
    sa.Column('criterion_id', sa.Integer(), nullable=False),
    sa.Column('criterion_name', sa.String(length=255), nullable=False),
    sa.Column('weight', sa.Numeric(precision=6, scale=2, asdecimal=False), nullable=False),
    sa.Column('selected_level_id', sa.Integer(), nullable=True),
    sa.Column('ai_suggested_score', sa.Numeric(precision=8, scale=2, asdecimal=False), nullable=True),
    sa.Column('final_score', sa.Numeric(precision=8, scale=2, asdecimal=False), nullable=False),
    sa.Column('weighted_score', sa.Numeric(precision=8, scale=2, asdecimal=False), nullable=False),
    sa.Column('ai_feedback', sa.Text(), nullable=False),
    sa.Column('final_feedback', sa.Text(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('improvement_suggestion', sa.Text(), nullable=False),
    sa.Column('modified_by_teacher', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['evaluation_id'], ['evaluations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('evaluation_id', 'criterion_id', name='uq_result_per_criterion')
    )
    op.create_table('evaluation_generations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evaluation_id', sa.Integer(), nullable=False),
    sa.Column('generation_number', sa.Integer(), nullable=False),
    sa.Column('prompt_version', sa.String(length=16), nullable=False),
    sa.Column('model_name', sa.String(length=128), nullable=False),
    sa.Column('prompt_context_summary', sa.JSON(), nullable=False),
    sa.Column('raw_response', sa.JSON(), nullable=True),
    sa.Column('validation_status', sa.Enum('VALID', 'INVALID_SCHEMA', 'INVALID_CRITERIA', 'INVALID_SCORE', 'EMPTY_RESPONSE', 'TIMEOUT', 'HTTP_ERROR', 'BLOCKED', name='generationvalidationstatus', native_enum=False, length=32), nullable=False),
    sa.Column('validation_errors', sa.JSON(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['evaluation_id'], ['evaluations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evaluation_revisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evaluation_id', sa.Integer(), nullable=False),
    sa.Column('criterion_result_id', sa.Integer(), nullable=True),
    sa.Column('field_changed', sa.Enum('SCORE', 'FEEDBACK', 'GENERAL_FEEDBACK', 'LEVEL', name='revisionfield', native_enum=False, length=32), nullable=False),
    sa.Column('previous_value', sa.Text(), nullable=False),
    sa.Column('new_value', sa.Text(), nullable=False),
    sa.Column('changed_by', sa.Integer(), nullable=False),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['criterion_result_id'], ['evaluation_criterion_results.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['evaluation_id'], ['evaluations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('evaluation_revisions')
    op.drop_table('evaluation_generations')
    op.drop_table('evaluation_criterion_results')
    op.drop_table('performance_levels')
    op.drop_table('evaluations')
    op.drop_table('submissions')
    op.drop_table('rubric_criteria')
    op.drop_table('rubrics')
    op.drop_table('assignments')
    op.drop_table('users')
    op.drop_table('lms_integrations')
    op.drop_table('incident_logs')
    # ### end Alembic commands ###
